import pyautogui as py
py.press("win")
py.write("edge")
py.press("enter")
py.sleep(2)
py.write("senai americana")
py.press("enter")
py.sleep(2)
py.click(673,376,button="left")
py.sleep(2)
py.click(1246,491,button="left")
py.sleep(2)
# print(py.position())
py.click(460,315,button="left")
py.sleep(1)
py.write("python")
py.sleep(1)
py.press("enter")
py.vscroll(-500)